### ISSUE TITLE
HTTP to Socks4?

### ISSUE THREAD

**Issue by h4ck1th4rd** [DKingAlpha/RPS#1]
Hi, I loved your work. its amazing code.
 
Just wonder can you make the requests check Socks4 and Send HTTP requests instead of HTTP proxies?

**Comment by DKingCN** [comment]
I dont know whether this is a socks proxy server or http proxy server. Basically it's forwarding recved traffic AS IT IS. 

You may want to find a module in pypi to provide socks4 proxy interface and then reimplement the ROTATING part.

**Comment by DKingAlpha** [comment]
refactored
