### ISSUE TITLE
There is a problem 

### ISSUE THREAD

**Issue by WalidMahmoud101** [DKingAlpha/RPS#4]
I want every requests = new proxy 1 per proxy

the problem is that each request works on one proxy for a certain time only

**Comment by DKingAlpha** [comment]
Bro I don't know what do you mean. But the code is short, you can try fix it by yourself.

**Comment by WalidMahmoud101** [comment]
i want help bro
if i try request post or get in curl , It gives Forwarding success Only one does not pass with the rest of the proxies
Knowing that I am using upstream proxy servers on burp suite

**Comment by DKingAlpha** [comment]
So you mean you want a port that forward your 1 requests to all proxy servers? like DDoS?

**Comment by WalidMahmoud101** [comment]
I am add 10 datacenter proxy server and send 10 get request via c# to local Burp Proxy (127.0.0.1:random port 8585-8595)
C# request - Burp Suite (127.0.0.1:(8585, 8595) - target site (check Ip address).
But all 10 requests used 1 upstream proxy for send request. 
How I can rotating upstream proxy for send 10 request via 10 added upstream proxy???

**Comment by DKingAlpha** [comment]
I don't think all 10 requests will go through a single proxy for current code.
But I am going to rewrite the code anyway. It's so crappy that I need to write a real socks5 server. I will let you know when I finished.

**Comment by WalidMahmoud101** [comment]
okey bro thank you so much

**Comment by WalidMahmoud101** [comment]
i have socks5 server if you need 
just send me your ip for link proxies in your address for test

**Comment by DKingAlpha** [comment]
Hi you can try again. It should go all random now.

Try modifying Ln.56 if you don't like the strategy allocating proxy,

**Comment by WalidMahmoud101** [comment]
Good just need to add time between each request and the other Because it takes a lot of time In every request of the proxy
just
